from django.contrib import admin
from .models import *
admin.site.register(students)
admin.site.register(Form1)
admin.site.register(Form2)
admin.site.register(Form3)
admin.site.register(Form4)
admin.site.register(Form5)
admin.site.register(Form6)
admin.site.register(Form7)
admin.site.register(Form8)
admin.site.register(Form9)
admin.site.register(Form10)
admin.site.register(teachers)
admin.site.register(every_teacher)