# Generated by Django 2.2.5 on 2022-04-06 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sbis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers', models.CharField(blank=True, max_length=20)),
                ('circular_title', models.CharField(blank=True, max_length=30)),
                ('circular', models.CharField(blank=True, max_length=100)),
                ('circular_pdf', models.FileField(blank=True, upload_to='')),
                ('worksheet_title', models.CharField(blank=True, max_length=30)),
                ('worksheet', models.CharField(blank=True, max_length=100)),
                ('worksheet_pdf', models.FileField(blank=True, upload_to='')),
                ('form', models.CharField(blank=True, default=None, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=10)),
                ('surname', models.CharField(blank=True, max_length=10)),
                ('form', models.CharField(blank=True, max_length=10)),
                ('roll_no', models.IntegerField()),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=10)),
                ('surname', models.CharField(blank=True, max_length=10)),
                ('form', models.CharField(blank=True, max_length=10)),
                ('subject1', models.CharField(blank=True, max_length=100)),
                ('subject2', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='every_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_pdf', models.FileField(blank=True, upload_to='')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbis.students')),
                ('teacher_name', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='sbis.teachers')),
            ],
        ),
    ]
