# Generated by Django 2.2.5 on 2022-03-12 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sbis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers', models.CharField(max_length=20)),
                ('circular_title', models.CharField(max_length=30)),
                ('circular', models.CharField(max_length=100)),
                ('circular_pdf', models.FileField(upload_to='')),
                ('worksheet_title', models.CharField(max_length=30)),
                ('worksheet', models.CharField(max_length=100)),
                ('worksheet_pdf', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=10)),
                ('form', models.CharField(max_length=10)),
                ('roll_no', models.IntegerField()),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sbis.Form')),
            ],
            bases=('sbis.form',),
        ),
        migrations.CreateModel(
            name='Form10',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sbis.Form')),
            ],
            bases=('sbis.form',),
        ),
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sbis.Form')),
            ],
            bases=('sbis.form',),
        ),
        migrations.CreateModel(
            name='Form3',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sbis.Form')),
            ],
            bases=('sbis.form',),
        ),
        migrations.CreateModel(
            name='Form4',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sbis.Form')),
            ],
            bases=('sbis.form',),
        ),
        migrations.CreateModel(
            name='Form5',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sbis.Form')),
            ],
            bases=('sbis.form',),
        ),
        migrations.CreateModel(
            name='Form6',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sbis.Form')),
            ],
            bases=('sbis.form',),
        ),
        migrations.CreateModel(
            name='Form7',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sbis.Form')),
            ],
            bases=('sbis.form',),
        ),
        migrations.CreateModel(
            name='Form8',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sbis.Form')),
            ],
            bases=('sbis.form',),
        ),
        migrations.CreateModel(
            name='Form9',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sbis.Form')),
            ],
            bases=('sbis.form',),
        ),
    ]
