# Generated by Django 2.2.5 on 2022-03-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbis', '0002_form_form1_form10_form2_form3_form4_form5_form6_form7_form8_form9_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=10)),
                ('surname', models.CharField(blank=True, max_length=10)),
                ('form', models.CharField(blank=True, max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='form',
            name='circular',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='circular_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='form',
            name='teachers',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='form',
            name='worksheet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='worksheet_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='form',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='surname',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
