# Generated by Django 2.2.5 on 2022-04-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbis', '0003_auto_20220328_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='every_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_pdf', models.FileField(blank=True, upload_to='')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbis.Form10')),
            ],
        ),
    ]
